### ISSUE TITLE
你这是修改DIYgod的repo吗

### ISSUE THREAD

**Issue by Rui-Tang** [Ovilia/cv#2]

**Comment by Ovilia** [comment]
不是，不过我刚刚看了下，风格的确有点类似。好像我们交换过友链呀，不知道是不是巧合哦，@DIYgod 来说明下？

**Comment by Rui-Tang** [comment]
奥，我看到就觉得风格有点像，然后就随口问了一下

发送自 Outlook

On Fri, Oct 16, 2015 at 9:30 AM -0700, "Wenli Zhang" notifications@github.com wrote:
不是，不过我刚刚看了下，风格的确有点类似。好像我们交换过友链呀，不知道是不是巧合哦，@DIYgod 来说明下？

---

**Comment by DIYgod** [comment]
是我参考了Ovilia学姐的风格，抱歉之前没有注明，刚刚在README里加上了,,,~~~

**Comment by Ovilia** [comment]
@DIYgod 没关系~
