### ISSUE TITLE
请问这个项目是怎么显示到zhangwenli.com/cv中的？

### ISSUE THREAD

**Issue by xiyebai** [Ovilia/cv#3]

**Comment by Ovilia** [comment]
https://github.com/Ovilia/ovilia.github.io/blob/master/CNAME

**Comment by xiyebai** [comment]
主页用CNAME指向zhangwenli.com，那么CV这另一个页面是怎么指向zhangwenli.com/cv的，表达问题不行，见谅啊，学姐 :)

**Comment by Ovilia** [comment]
主页用 CNAME 指向 zhangwenli.com 后，ovilia.github.io 将跳转到 zhangwenli.com 。
其他项目 xxx 的 gh-pages 分支将会自动对应到 ovilia.github.io/xxx 。
还不理解的话看这个：https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
